input {
  file {
    # Chemin vers le CSV dans le conteneur Docker
    path => "/data/Movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => plain { charset => "UTF-8" }
  }
}

filter {
  # Découper chaque ligne du CSV selon les colonnes
  csv {
    separator => ","
    quote_char => '"'
    columns => [
      "id", "title", "genres", "original_language",
      "overview", "popularity", "production_companies",
      "release_date", "budget", "revenue", "runtime",
      "status", "tagline", "vote_average", "vote_count",
      "credits", "keywords", "poster_path",
      "backdrop_path", "recommendations"
    ]
  }

  # Supprimer la ligne d'en-tête du CSV
  if [id] == "id" {
    drop { }
  }

  # Supprimer les champs techniques ajoutés par Logstash
  mutate {
    remove_field => ["@version", "host", "log", "event", "message"]
  }

  # on est crée une copie, l'original devient la version raw et la copie devient la version clean
  clone {
    clones => ["clean"]
  }

  # application des règles de nettoyage (F3) uniquement sur le clone "clean"
  if "clean" in [tags] {
    
    # traitement des anomalies : on retire les événements sans titre ou date de sortie
    if ![title] or ![release_date] {
      drop { }
    }

    # conversion de types pour les métriques numériques
    mutate {
      convert => {
        "popularity" => "float"
        "vote_average" => "float"
        "vote_count" => "integer"
        "budget" => "float"
        "revenue" => "float"
        "runtime" => "float"
      }
      
      # normalisation : on passe la langue en minuscules
      lowercase => ["original_language"]

      # séparation des listes par tiret
      split => {
        "genres" => "-"
        "production_companies" => "-"
        "credits" => "-"
        "keywords" => "-"
        "recommendations" => "-"
      }
    }

    # parsing de la date (format yyyy-MM-dd)
    date {
      match => ["release_date", "yyyy-MM-dd"]
      target => "release_date"
      timezone => "UTC"
    }

  }
}

output {

  if "clean" in [tags] {
    # Indexation des données nettoyées et typées pour le clone "clean"
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "movies_clean"
      document_id => "%{id}"
    }
  } else {
    # Indexation de l'ingestion brute pour le clone "raw"
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "movies_raw"
      document_id => "%{id}" 
    }
  }
}