input {
  file {
    # Chemin vers le CSV dans le conteneur Docker
    path => "/data/Movies.csv"

    start_position => "beginning"

    sincedb_path => "/dev/null"

    codec => plain { charset => "UTF-8" }
  }
}

filter {
  # Découper chaque ligne du CSV selon les colonnes
  csv {
    separator => ","
    quote_char => '"'
    columns => [
      "id", "title", "genres", "original_language",
      "overview", "popularity", "production_companies",
      "release_date", "budget", "revenue", "runtime",
      "status", "tagline", "vote_average", "vote_count",
      "credits", "keywords", "poster_path",
      "backdrop_path", "recommendations"
    ]
  }

  # Supprimer la ligne d'en-tête du CSV
  if [id] == "id" {
    drop { }
  }

  # Supprimer les champs techniques ajoutés par Logstash
  mutate {
    remove_field => ["@version", "host", "log", "event", "message"]
  }
}

output {
  # Envoyer dans Elasticsearch dans l'index movies_raw
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_raw"
  }

  # Afficher dans les logs pour vérifier (optionnel)
  stdout { codec => dots }
}